[build.environment]
  HUGO_VERSION = "0.84.2"

[build]
  command = "make build"
  publish = "public"

[context.production]
  publish = "public"
  command = "make build"

[context.deploy-preview]
  publish = "public"
  command = "make build-preview"

[context.staging]
  publish = "public"
  command = "make build"
  
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
	[plugins.inputs]
	debug = true

# [dev]
#   framework = "#custom"
#   # only start Hugo, `netlify dev` builds/serves functions itself
#   command = "npm start"
#   # swap ports to keep consistent w/ normal local server
#   targetPort = 1314
#   port = 1313
#   # don't launch browser automatically
#   autoLaunch = false

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  baseUrl = "https://docs.rackspace.com/blog"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://docs.rackspace.com/blog"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Enabled providers to submit sitemap to (optional, default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
	providers = [
		"google"
	]

[[plugins]]
  package = "netlify-plugin-a11y"

  # all inputs are optional, we just show you the defaults below
  [plugins.inputs]
  
  # required config
  checkPaths = ['/'] # you can give an array of directories or paths to html files, that you want to run a11y checks on

  # optional config
  # ignoreDirectories = ['/admin']  # explicitly ignore these directories

  resultMode = "warn" # is "error" by default

  # Developer only
  debugMode = true # extra logging for plugin developers

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  # [plugins.inputs.thresholds]
  #   performance = 0.9
  #   accessibility = 0.9
  #   best-practices = 0.9
  #   seo = 0.9
  #   pwa = 0.9